- name: Vars Test playbook
  hosts: localhost
  vars:
    namer: "Sudhakar"
    city: "Vijayawada"
    Job: "Software employee"
    domain: "SDET"
  tasks:
  - name: indian-playbooker
    ansible.builtin.debug:
      msg: "i am sudhakar andliving in {{city}} doing job as {{Job}}as a {{domain}}"