- name: Vars Test playbook
  hosts: localhost
  vars_files:
  - variableFiles.yaml
  tasks:
  - name: indian-playbooker
    vars:
      namer: "Sudhakar Reddy Ponugoti"
    ansible.builtin.debug:
      msg: "i am {{namer}} andliving in {{city}} doing job as {{Job}}as a {{domain}}"