- name: Vars Test playbook
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false # user can see the user name value 
  - name: PASSWORD
    prompt: please enter your password
    private: true # user can not see the password value
  tasks:
  - name: indian-playbooker
    ansible.builtin.debug:
      msg: "username is {{USERNAME}}, password is {{PASSWORD}}"